import React from 'react'
import Script from 'next/script'

const page = () => {
  return (
   
    <div>

    <Script>
        {` alert("Welcome to About Page");`}
    </Script>
        About Page
    </div>
  )
}

export default page

export const metadata = {
    title: " About Facebook - Connect With the World",
    description: "Generated by create next app",
  };